### ISSUE TITLE
Seems to conflict with the popular Repeat Attack Plugin

### ISSUE THREAD

**Issue by solsticesolutions** [Arachnid/df-vizier#10]
Vizier won't start performing tasks if repeat attack is open, possibly there is a conflict there.

Repeat Attack doesn't stop working when plugin is closed so df page has to be refreshed to load vizier after using repeat attack.

**Comment by Arachnid** [comment]
Vizier presently only does a run if there are no pending transactions - to prevent queueing up transactions faster than they can be executed. It's likely repeat attack usually has pending transactions.

**Comment by Arachnid** [comment]
Closing, as we can't do anything about it for now.
